# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/CubePrimitive.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import Color_pb2 as foxglove_dot_Color__pb2
from foxglove import Pose_pb2 as foxglove_dot_Pose__pb2
from foxglove import Vector3_pb2 as foxglove_dot_Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66oxglove/CubePrimitive.proto\x12\x08\x66oxglove\x1a\x14\x66oxglove/Color.proto\x1a\x13\x66oxglove/Pose.proto\x1a\x16\x66oxglove/Vector3.proto\"n\n\rCubePrimitive\x12\x1c\n\x04pose\x18\x01 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x1f\n\x04size\x18\x02 \x01(\x0b\x32\x11.foxglove.Vector3\x12\x1e\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0f.foxglove.Colorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxglove.CubePrimitive_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUBEPRIMITIVE._serialized_start=109
  _CUBEPRIMITIVE._serialized_end=219
# @@protoc_insertion_point(module_scope)
