# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/GeoJSON.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foxglove/GeoJSON.proto',
  package='foxglove',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x66oxglove/GeoJSON.proto\x12\x08\x66oxglove\"\x1a\n\x07GeoJSON\x12\x0f\n\x07geojson\x18\x01 \x01(\tb\x06proto3'
)




_GEOJSON = _descriptor.Descriptor(
  name='GeoJSON',
  full_name='foxglove.GeoJSON',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='geojson', full_name='foxglove.GeoJSON.geojson', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['GeoJSON'] = _GEOJSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoJSON = _reflection.GeneratedProtocolMessageType('GeoJSON', (_message.Message,), {
  'DESCRIPTOR' : _GEOJSON,
  '__module__' : 'foxglove.GeoJSON_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.GeoJSON)
  })
_sym_db.RegisterMessage(GeoJSON)


# @@protoc_insertion_point(module_scope)
