# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/Grid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import PackedElementField_pb2 as foxglove_dot_PackedElementField__pb2
from foxglove import Pose_pb2 as foxglove_dot_Pose__pb2
from foxglove import Vector2_pb2 as foxglove_dot_Vector2__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='foxglove/Grid.proto',
  package='foxglove',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66oxglove/Grid.proto\x12\x08\x66oxglove\x1a!foxglove/PackedElementField.proto\x1a\x13\x66oxglove/Pose.proto\x1a\x16\x66oxglove/Vector2.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n\x04Grid\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x1c\n\x04pose\x18\x03 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x14\n\x0c\x63olumn_count\x18\x04 \x01(\x07\x12$\n\tcell_size\x18\x05 \x01(\x0b\x32\x11.foxglove.Vector2\x12\x12\n\nrow_stride\x18\x06 \x01(\x07\x12\x13\n\x0b\x63\x65ll_stride\x18\x07 \x01(\x07\x12,\n\x06\x66ields\x18\x08 \x03(\x0b\x32\x1c.foxglove.PackedElementField\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\x0c\x62\x06proto3'
  ,
  dependencies=[foxglove_dot_PackedElementField__pb2.DESCRIPTOR,foxglove_dot_Pose__pb2.DESCRIPTOR,foxglove_dot_Vector2__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_GRID = _descriptor.Descriptor(
  name='Grid',
  full_name='foxglove.Grid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='foxglove.Grid.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='foxglove.Grid.frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='foxglove.Grid.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_count', full_name='foxglove.Grid.column_count', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_size', full_name='foxglove.Grid.cell_size', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row_stride', full_name='foxglove.Grid.row_stride', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_stride', full_name='foxglove.Grid.cell_stride', index=6,
      number=7, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='foxglove.Grid.fields', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='foxglove.Grid.data', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=409,
)

_GRID.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GRID.fields_by_name['pose'].message_type = foxglove_dot_Pose__pb2._POSE
_GRID.fields_by_name['cell_size'].message_type = foxglove_dot_Vector2__pb2._VECTOR2
_GRID.fields_by_name['fields'].message_type = foxglove_dot_PackedElementField__pb2._PACKEDELEMENTFIELD
DESCRIPTOR.message_types_by_name['Grid'] = _GRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Grid = _reflection.GeneratedProtocolMessageType('Grid', (_message.Message,), {
  'DESCRIPTOR' : _GRID,
  '__module__' : 'foxglove.Grid_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.Grid)
  })
_sym_db.RegisterMessage(Grid)


# @@protoc_insertion_point(module_scope)
