# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/ImageAnnotations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import CircleAnnotation_pb2 as foxglove_dot_CircleAnnotation__pb2
from foxglove import PointsAnnotation_pb2 as foxglove_dot_PointsAnnotation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66oxglove/ImageAnnotations.proto\x12\x08\x66oxglove\x1a\x1f\x66oxglove/CircleAnnotation.proto\x1a\x1f\x66oxglove/PointsAnnotation.proto\"k\n\x10ImageAnnotations\x12+\n\x07\x63ircles\x18\x01 \x03(\x0b\x32\x1a.foxglove.CircleAnnotation\x12*\n\x06points\x18\x02 \x03(\x0b\x32\x1a.foxglove.PointsAnnotationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxglove.ImageAnnotations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEANNOTATIONS._serialized_start=111
  _IMAGEANNOTATIONS._serialized_end=218
# @@protoc_insertion_point(module_scope)
