# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/LaserScan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import Pose_pb2 as foxglove_dot_Pose__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66oxglove/LaserScan.proto\x12\x08\x66oxglove\x1a\x13\x66oxglove/Pose.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n\tLaserScan\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x1c\n\x04pose\x18\x03 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x13\n\x0bstart_angle\x18\x04 \x01(\x01\x12\x11\n\tend_angle\x18\x05 \x01(\x01\x12\x0e\n\x06ranges\x18\x06 \x03(\x01\x12\x13\n\x0bintensities\x18\x07 \x03(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxglove.LaserScan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LASERSCAN._serialized_start=93
  _LASERSCAN._serialized_end=276
# @@protoc_insertion_point(module_scope)
