# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/LocationFix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foxglove/LocationFix.proto',
  package='foxglove',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x66oxglove/LocationFix.proto\x12\x08\x66oxglove\"\x89\x02\n\x0bLocationFix\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x1b\n\x13position_covariance\x18\x04 \x03(\x01\x12N\n\x18position_covariance_type\x18\x05 \x01(\x0e\x32,.foxglove.LocationFix.PositionCovarianceType\"V\n\x16PositionCovarianceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x41PPROXIMATED\x10\x01\x12\x12\n\x0e\x44IAGONAL_KNOWN\x10\x02\x12\t\n\x05KNOWN\x10\x03\x62\x06proto3'
)



_LOCATIONFIX_POSITIONCOVARIANCETYPE = _descriptor.EnumDescriptor(
  name='PositionCovarianceType',
  full_name='foxglove.LocationFix.PositionCovarianceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='APPROXIMATED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIAGONAL_KNOWN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KNOWN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=220,
  serialized_end=306,
)
_sym_db.RegisterEnumDescriptor(_LOCATIONFIX_POSITIONCOVARIANCETYPE)


_LOCATIONFIX = _descriptor.Descriptor(
  name='LocationFix',
  full_name='foxglove.LocationFix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='foxglove.LocationFix.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='foxglove.LocationFix.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='foxglove.LocationFix.altitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_covariance', full_name='foxglove.LocationFix.position_covariance', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_covariance_type', full_name='foxglove.LocationFix.position_covariance_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOCATIONFIX_POSITIONCOVARIANCETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=306,
)

_LOCATIONFIX.fields_by_name['position_covariance_type'].enum_type = _LOCATIONFIX_POSITIONCOVARIANCETYPE
_LOCATIONFIX_POSITIONCOVARIANCETYPE.containing_type = _LOCATIONFIX
DESCRIPTOR.message_types_by_name['LocationFix'] = _LOCATIONFIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationFix = _reflection.GeneratedProtocolMessageType('LocationFix', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONFIX,
  '__module__' : 'foxglove.LocationFix_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.LocationFix)
  })
_sym_db.RegisterMessage(LocationFix)


# @@protoc_insertion_point(module_scope)
