"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import foxglove.Quaternion_pb2
import foxglove.Vector3_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Pose(google.protobuf.message.Message):
    """A position and orientation for an object or reference frame in 3D space"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    POSITION_FIELD_NUMBER: builtins.int
    ORIENTATION_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> foxglove.Vector3_pb2.Vector3:
        """Point denoting position in 3D space"""
        pass
    @property
    def orientation(self) -> foxglove.Quaternion_pb2.Quaternion:
        """Quaternion denoting orientation in 3D space"""
        pass
    def __init__(self,
        *,
        position: typing.Optional[foxglove.Vector3_pb2.Vector3] = ...,
        orientation: typing.Optional[foxglove.Quaternion_pb2.Quaternion] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["orientation",b"orientation","position",b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["orientation",b"orientation","position",b"position"]) -> None: ...
global___Pose = Pose
