# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/SceneEntity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import ArrowPrimitive_pb2 as foxglove_dot_ArrowPrimitive__pb2
from foxglove import CubePrimitive_pb2 as foxglove_dot_CubePrimitive__pb2
from foxglove import CylinderPrimitive_pb2 as foxglove_dot_CylinderPrimitive__pb2
from foxglove import KeyValuePair_pb2 as foxglove_dot_KeyValuePair__pb2
from foxglove import LinePrimitive_pb2 as foxglove_dot_LinePrimitive__pb2
from foxglove import ModelPrimitive_pb2 as foxglove_dot_ModelPrimitive__pb2
from foxglove import SpherePrimitive_pb2 as foxglove_dot_SpherePrimitive__pb2
from foxglove import TextPrimitive_pb2 as foxglove_dot_TextPrimitive__pb2
from foxglove import TriangleListPrimitive_pb2 as foxglove_dot_TriangleListPrimitive__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66oxglove/SceneEntity.proto\x12\x08\x66oxglove\x1a\x1d\x66oxglove/ArrowPrimitive.proto\x1a\x1c\x66oxglove/CubePrimitive.proto\x1a foxglove/CylinderPrimitive.proto\x1a\x1b\x66oxglove/KeyValuePair.proto\x1a\x1c\x66oxglove/LinePrimitive.proto\x1a\x1d\x66oxglove/ModelPrimitive.proto\x1a\x1e\x66oxglove/SpherePrimitive.proto\x1a\x1c\x66oxglove/TextPrimitive.proto\x1a$foxglove/TriangleListPrimitive.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x04\n\x0bSceneEntity\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12+\n\x08lifetime\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0c\x66rame_locked\x18\x05 \x01(\x08\x12(\n\x08metadata\x18\x06 \x03(\x0b\x32\x16.foxglove.KeyValuePair\x12(\n\x06\x61rrows\x18\x07 \x03(\x0b\x32\x18.foxglove.ArrowPrimitive\x12&\n\x05\x63ubes\x18\x08 \x03(\x0b\x32\x17.foxglove.CubePrimitive\x12*\n\x07spheres\x18\t \x03(\x0b\x32\x19.foxglove.SpherePrimitive\x12.\n\tcylinders\x18\n \x03(\x0b\x32\x1b.foxglove.CylinderPrimitive\x12&\n\x05lines\x18\x0b \x03(\x0b\x32\x17.foxglove.LinePrimitive\x12\x32\n\ttriangles\x18\x0c \x03(\x0b\x32\x1f.foxglove.TriangleListPrimitive\x12&\n\x05texts\x18\r \x03(\x0b\x32\x17.foxglove.TextPrimitive\x12(\n\x06models\x18\x0e \x03(\x0b\x32\x18.foxglove.ModelPrimitiveb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxglove.SceneEntity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEENTITY._serialized_start=391
  _SCENEENTITY._serialized_end=938
# @@protoc_insertion_point(module_scope)
