FROM ubuntu:jammy AS base

# https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    ca-certificates \
    curl \
    cmake \
    gnupg \
    make \
    perl \
    python3 \
    python3-pip \
    clang \
    clang-format

ENV CC=clang
ENV CXX=clang++

WORKDIR /src

FROM base as build
RUN pip --no-cache-dir install conan
RUN conan profile detect --force

FROM build as build_examples
COPY ./foxglove-websocket/conanfile.py /src/foxglove-websocket/conanfile.py
ARG CPPSTD=17
RUN conan install foxglove-websocket -s compiler.cppstd=$CPPSTD --build=missing
COPY ./foxglove-websocket /src/foxglove-websocket/
RUN conan create foxglove-websocket -s compiler.cppstd=$CPPSTD
COPY ./examples/conanfile.py /src/examples/conanfile.py
RUN conan install examples --output-folder examples/build --build=missing -s compiler.cppstd=$CPPSTD -s build_type=Debug

FROM build_examples AS examples
COPY --from=build_examples /src /src
COPY ./examples /src/examples
COPY --from=build_examples /src/examples/build/ /src/examples/build/
RUN conan build examples --output-folder examples/ -s compiler.cppstd=$CPPSTD -s build_type=Debug

FROM examples AS example_server_protobuf
CMD ["examples/build/Debug/example_server_protobuf"]

FROM examples AS example_server_flatbuffers
CMD ["examples/build/Debug/example_server_flatbuffers", "/src/examples/autogenerated_flatbuffers/SceneUpdate.bfbs"]
