services:
  base:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: base

  build:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: build

  example_server_protobuf:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: example_server_protobuf
    ports:
      - "8765:8765"

  example_server_flatbuffers:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: example_server_flatbuffers
    ports:
      - "8765:8765"

  example_server_json:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: example_server_json
    ports:
      - "8765:8765"

  example_server_perf_test:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: example_server_perf_test
    network_mode: "host"  # Use host network for better perfomance

  example_client_perf_test:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: example_client_perf_test
    network_mode: "host"  # Use host network for better perfomance
