# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExampleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExampleMsg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x45xampleMsg.proto\"(\n\nExampleMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x62\x06proto3'
)




_EXAMPLEMSG = _descriptor.Descriptor(
  name='ExampleMsg',
  full_name='ExampleMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ExampleMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='ExampleMsg.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['ExampleMsg'] = _EXAMPLEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleMsg = _reflection.GeneratedProtocolMessageType('ExampleMsg', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEMSG,
  '__module__' : 'ExampleMsg_pb2'
  # @@protoc_insertion_point(class_scope:ExampleMsg)
  })
_sym_db.RegisterMessage(ExampleMsg)


# @@protoc_insertion_point(module_scope)
