// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/ArrowPrimitive.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_foxglove_2fArrowPrimitive_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_foxglove_2fArrowPrimitive_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/Color.pb.h"
#include "foxglove/Pose.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_foxglove_2fArrowPrimitive_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_foxglove_2fArrowPrimitive_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_foxglove_2fArrowPrimitive_2eproto;
namespace foxglove {
class ArrowPrimitive;
struct ArrowPrimitiveDefaultTypeInternal;
extern ArrowPrimitiveDefaultTypeInternal _ArrowPrimitive_default_instance_;
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> ::foxglove::ArrowPrimitive* Arena::CreateMaybeMessage<::foxglove::ArrowPrimitive>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace foxglove {

// ===================================================================

class ArrowPrimitive final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:foxglove.ArrowPrimitive) */ {
 public:
  inline ArrowPrimitive() : ArrowPrimitive(nullptr) {}
  ~ArrowPrimitive() override;
  explicit PROTOBUF_CONSTEXPR ArrowPrimitive(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ArrowPrimitive(const ArrowPrimitive& from);
  ArrowPrimitive(ArrowPrimitive&& from) noexcept
    : ArrowPrimitive() {
    *this = ::std::move(from);
  }

  inline ArrowPrimitive& operator=(const ArrowPrimitive& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArrowPrimitive& operator=(ArrowPrimitive&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArrowPrimitive& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArrowPrimitive* internal_default_instance() {
    return reinterpret_cast<const ArrowPrimitive*>(
               &_ArrowPrimitive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ArrowPrimitive& a, ArrowPrimitive& b) {
    a.Swap(&b);
  }
  inline void Swap(ArrowPrimitive* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArrowPrimitive* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArrowPrimitive* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ArrowPrimitive>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ArrowPrimitive& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ArrowPrimitive& from) {
    ArrowPrimitive::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArrowPrimitive* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "foxglove.ArrowPrimitive";
  }
  protected:
  explicit ArrowPrimitive(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoseFieldNumber = 1,
    kColorFieldNumber = 6,
    kShaftLengthFieldNumber = 2,
    kShaftDiameterFieldNumber = 3,
    kHeadLengthFieldNumber = 4,
    kHeadDiameterFieldNumber = 5,
  };
  // .foxglove.Pose pose = 1;
  bool has_pose() const;
  private:
  bool _internal_has_pose() const;
  public:
  void clear_pose();
  const ::foxglove::Pose& pose() const;
  PROTOBUF_NODISCARD ::foxglove::Pose* release_pose();
  ::foxglove::Pose* mutable_pose();
  void set_allocated_pose(::foxglove::Pose* pose);
  private:
  const ::foxglove::Pose& _internal_pose() const;
  ::foxglove::Pose* _internal_mutable_pose();
  public:
  void unsafe_arena_set_allocated_pose(
      ::foxglove::Pose* pose);
  ::foxglove::Pose* unsafe_arena_release_pose();

  // .foxglove.Color color = 6;
  bool has_color() const;
  private:
  bool _internal_has_color() const;
  public:
  void clear_color();
  const ::foxglove::Color& color() const;
  PROTOBUF_NODISCARD ::foxglove::Color* release_color();
  ::foxglove::Color* mutable_color();
  void set_allocated_color(::foxglove::Color* color);
  private:
  const ::foxglove::Color& _internal_color() const;
  ::foxglove::Color* _internal_mutable_color();
  public:
  void unsafe_arena_set_allocated_color(
      ::foxglove::Color* color);
  ::foxglove::Color* unsafe_arena_release_color();

  // double shaft_length = 2;
  void clear_shaft_length();
  double shaft_length() const;
  void set_shaft_length(double value);
  private:
  double _internal_shaft_length() const;
  void _internal_set_shaft_length(double value);
  public:

  // double shaft_diameter = 3;
  void clear_shaft_diameter();
  double shaft_diameter() const;
  void set_shaft_diameter(double value);
  private:
  double _internal_shaft_diameter() const;
  void _internal_set_shaft_diameter(double value);
  public:

  // double head_length = 4;
  void clear_head_length();
  double head_length() const;
  void set_head_length(double value);
  private:
  double _internal_head_length() const;
  void _internal_set_head_length(double value);
  public:

  // double head_diameter = 5;
  void clear_head_diameter();
  double head_diameter() const;
  void set_head_diameter(double value);
  private:
  double _internal_head_diameter() const;
  void _internal_set_head_diameter(double value);
  public:

  // @@protoc_insertion_point(class_scope:foxglove.ArrowPrimitive)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::foxglove::Pose* pose_;
    ::foxglove::Color* color_;
    double shaft_length_;
    double shaft_diameter_;
    double head_length_;
    double head_diameter_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_foxglove_2fArrowPrimitive_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ArrowPrimitive

// .foxglove.Pose pose = 1;
inline bool ArrowPrimitive::_internal_has_pose() const {
  return this != internal_default_instance() && _impl_.pose_ != nullptr;
}
inline bool ArrowPrimitive::has_pose() const {
  return _internal_has_pose();
}
inline const ::foxglove::Pose& ArrowPrimitive::_internal_pose() const {
  const ::foxglove::Pose* p = _impl_.pose_;
  return p != nullptr ? *p : reinterpret_cast<const ::foxglove::Pose&>(
      ::foxglove::_Pose_default_instance_);
}
inline const ::foxglove::Pose& ArrowPrimitive::pose() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.pose)
  return _internal_pose();
}
inline void ArrowPrimitive::unsafe_arena_set_allocated_pose(
    ::foxglove::Pose* pose) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pose_);
  }
  _impl_.pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:foxglove.ArrowPrimitive.pose)
}
inline ::foxglove::Pose* ArrowPrimitive::release_pose() {
  
  ::foxglove::Pose* temp = _impl_.pose_;
  _impl_.pose_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::foxglove::Pose* ArrowPrimitive::unsafe_arena_release_pose() {
  // @@protoc_insertion_point(field_release:foxglove.ArrowPrimitive.pose)
  
  ::foxglove::Pose* temp = _impl_.pose_;
  _impl_.pose_ = nullptr;
  return temp;
}
inline ::foxglove::Pose* ArrowPrimitive::_internal_mutable_pose() {
  
  if (_impl_.pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::foxglove::Pose>(GetArenaForAllocation());
    _impl_.pose_ = p;
  }
  return _impl_.pose_;
}
inline ::foxglove::Pose* ArrowPrimitive::mutable_pose() {
  ::foxglove::Pose* _msg = _internal_mutable_pose();
  // @@protoc_insertion_point(field_mutable:foxglove.ArrowPrimitive.pose)
  return _msg;
}
inline void ArrowPrimitive::set_allocated_pose(::foxglove::Pose* pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pose_);
  }
  if (pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose));
    if (message_arena != submessage_arena) {
      pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:foxglove.ArrowPrimitive.pose)
}

// double shaft_length = 2;
inline void ArrowPrimitive::clear_shaft_length() {
  _impl_.shaft_length_ = 0;
}
inline double ArrowPrimitive::_internal_shaft_length() const {
  return _impl_.shaft_length_;
}
inline double ArrowPrimitive::shaft_length() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.shaft_length)
  return _internal_shaft_length();
}
inline void ArrowPrimitive::_internal_set_shaft_length(double value) {
  
  _impl_.shaft_length_ = value;
}
inline void ArrowPrimitive::set_shaft_length(double value) {
  _internal_set_shaft_length(value);
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.shaft_length)
}

// double shaft_diameter = 3;
inline void ArrowPrimitive::clear_shaft_diameter() {
  _impl_.shaft_diameter_ = 0;
}
inline double ArrowPrimitive::_internal_shaft_diameter() const {
  return _impl_.shaft_diameter_;
}
inline double ArrowPrimitive::shaft_diameter() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.shaft_diameter)
  return _internal_shaft_diameter();
}
inline void ArrowPrimitive::_internal_set_shaft_diameter(double value) {
  
  _impl_.shaft_diameter_ = value;
}
inline void ArrowPrimitive::set_shaft_diameter(double value) {
  _internal_set_shaft_diameter(value);
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.shaft_diameter)
}

// double head_length = 4;
inline void ArrowPrimitive::clear_head_length() {
  _impl_.head_length_ = 0;
}
inline double ArrowPrimitive::_internal_head_length() const {
  return _impl_.head_length_;
}
inline double ArrowPrimitive::head_length() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.head_length)
  return _internal_head_length();
}
inline void ArrowPrimitive::_internal_set_head_length(double value) {
  
  _impl_.head_length_ = value;
}
inline void ArrowPrimitive::set_head_length(double value) {
  _internal_set_head_length(value);
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.head_length)
}

// double head_diameter = 5;
inline void ArrowPrimitive::clear_head_diameter() {
  _impl_.head_diameter_ = 0;
}
inline double ArrowPrimitive::_internal_head_diameter() const {
  return _impl_.head_diameter_;
}
inline double ArrowPrimitive::head_diameter() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.head_diameter)
  return _internal_head_diameter();
}
inline void ArrowPrimitive::_internal_set_head_diameter(double value) {
  
  _impl_.head_diameter_ = value;
}
inline void ArrowPrimitive::set_head_diameter(double value) {
  _internal_set_head_diameter(value);
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.head_diameter)
}

// .foxglove.Color color = 6;
inline bool ArrowPrimitive::_internal_has_color() const {
  return this != internal_default_instance() && _impl_.color_ != nullptr;
}
inline bool ArrowPrimitive::has_color() const {
  return _internal_has_color();
}
inline const ::foxglove::Color& ArrowPrimitive::_internal_color() const {
  const ::foxglove::Color* p = _impl_.color_;
  return p != nullptr ? *p : reinterpret_cast<const ::foxglove::Color&>(
      ::foxglove::_Color_default_instance_);
}
inline const ::foxglove::Color& ArrowPrimitive::color() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.color)
  return _internal_color();
}
inline void ArrowPrimitive::unsafe_arena_set_allocated_color(
    ::foxglove::Color* color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.color_);
  }
  _impl_.color_ = color;
  if (color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:foxglove.ArrowPrimitive.color)
}
inline ::foxglove::Color* ArrowPrimitive::release_color() {
  
  ::foxglove::Color* temp = _impl_.color_;
  _impl_.color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::foxglove::Color* ArrowPrimitive::unsafe_arena_release_color() {
  // @@protoc_insertion_point(field_release:foxglove.ArrowPrimitive.color)
  
  ::foxglove::Color* temp = _impl_.color_;
  _impl_.color_ = nullptr;
  return temp;
}
inline ::foxglove::Color* ArrowPrimitive::_internal_mutable_color() {
  
  if (_impl_.color_ == nullptr) {
    auto* p = CreateMaybeMessage<::foxglove::Color>(GetArenaForAllocation());
    _impl_.color_ = p;
  }
  return _impl_.color_;
}
inline ::foxglove::Color* ArrowPrimitive::mutable_color() {
  ::foxglove::Color* _msg = _internal_mutable_color();
  // @@protoc_insertion_point(field_mutable:foxglove.ArrowPrimitive.color)
  return _msg;
}
inline void ArrowPrimitive::set_allocated_color(::foxglove::Color* color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.color_);
  }
  if (color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(color));
    if (message_arena != submessage_arena) {
      color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, color, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.color_ = color;
  // @@protoc_insertion_point(field_set_allocated:foxglove.ArrowPrimitive.color)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_foxglove_2fArrowPrimitive_2eproto
