// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/PointsAnnotation.proto

#include "foxglove/PointsAnnotation.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace foxglove {
PROTOBUF_CONSTEXPR PointsAnnotation::PointsAnnotation(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.points_)*/{}
  , /*decltype(_impl_.outline_colors_)*/{}
  , /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.outline_color_)*/nullptr
  , /*decltype(_impl_.fill_color_)*/nullptr
  , /*decltype(_impl_.thickness_)*/0
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PointsAnnotationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PointsAnnotationDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointsAnnotationDefaultTypeInternal() {}
  union {
    PointsAnnotation _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointsAnnotationDefaultTypeInternal _PointsAnnotation_default_instance_;
}  // namespace foxglove
static ::_pb::Metadata file_level_metadata_foxglove_2fPointsAnnotation_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_foxglove_2fPointsAnnotation_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_foxglove_2fPointsAnnotation_2eproto = nullptr;

const uint32_t TableStruct_foxglove_2fPointsAnnotation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.points_),
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.outline_color_),
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.outline_colors_),
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.fill_color_),
  PROTOBUF_FIELD_OFFSET(::foxglove::PointsAnnotation, _impl_.thickness_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::foxglove::PointsAnnotation)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::foxglove::_PointsAnnotation_default_instance_._instance,
};

const char descriptor_table_protodef_foxglove_2fPointsAnnotation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037foxglove/PointsAnnotation.proto\022\010foxgl"
  "ove\032\024foxglove/Color.proto\032\025foxglove/Poin"
  "t2.proto\032\037google/protobuf/timestamp.prot"
  "o\"\352\002\n\020PointsAnnotation\022-\n\ttimestamp\030\001 \001("
  "\0132\032.google.protobuf.Timestamp\022-\n\004type\030\002 "
  "\001(\0162\037.foxglove.PointsAnnotation.Type\022 \n\006"
  "points\030\003 \003(\0132\020.foxglove.Point2\022&\n\routlin"
  "e_color\030\004 \001(\0132\017.foxglove.Color\022\'\n\016outlin"
  "e_colors\030\005 \003(\0132\017.foxglove.Color\022#\n\nfill_"
  "color\030\006 \001(\0132\017.foxglove.Color\022\021\n\tthicknes"
  "s\030\007 \001(\001\"M\n\004Type\022\013\n\007UNKNOWN\020\000\022\n\n\006POINTS\020\001"
  "\022\r\n\tLINE_LOOP\020\002\022\016\n\nLINE_STRIP\020\003\022\r\n\tLINE_"
  "LIST\020\004b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_foxglove_2fPointsAnnotation_2eproto_deps[3] = {
  &::descriptor_table_foxglove_2fColor_2eproto,
  &::descriptor_table_foxglove_2fPoint2_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_foxglove_2fPointsAnnotation_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_foxglove_2fPointsAnnotation_2eproto = {
    false, false, 494, descriptor_table_protodef_foxglove_2fPointsAnnotation_2eproto,
    "foxglove/PointsAnnotation.proto",
    &descriptor_table_foxglove_2fPointsAnnotation_2eproto_once, descriptor_table_foxglove_2fPointsAnnotation_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_foxglove_2fPointsAnnotation_2eproto::offsets,
    file_level_metadata_foxglove_2fPointsAnnotation_2eproto, file_level_enum_descriptors_foxglove_2fPointsAnnotation_2eproto,
    file_level_service_descriptors_foxglove_2fPointsAnnotation_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_foxglove_2fPointsAnnotation_2eproto_getter() {
  return &descriptor_table_foxglove_2fPointsAnnotation_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_foxglove_2fPointsAnnotation_2eproto(&descriptor_table_foxglove_2fPointsAnnotation_2eproto);
namespace foxglove {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PointsAnnotation_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_foxglove_2fPointsAnnotation_2eproto);
  return file_level_enum_descriptors_foxglove_2fPointsAnnotation_2eproto[0];
}
bool PointsAnnotation_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr PointsAnnotation_Type PointsAnnotation::UNKNOWN;
constexpr PointsAnnotation_Type PointsAnnotation::POINTS;
constexpr PointsAnnotation_Type PointsAnnotation::LINE_LOOP;
constexpr PointsAnnotation_Type PointsAnnotation::LINE_STRIP;
constexpr PointsAnnotation_Type PointsAnnotation::LINE_LIST;
constexpr PointsAnnotation_Type PointsAnnotation::Type_MIN;
constexpr PointsAnnotation_Type PointsAnnotation::Type_MAX;
constexpr int PointsAnnotation::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class PointsAnnotation::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const PointsAnnotation* msg);
  static const ::foxglove::Color& outline_color(const PointsAnnotation* msg);
  static const ::foxglove::Color& fill_color(const PointsAnnotation* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
PointsAnnotation::_Internal::timestamp(const PointsAnnotation* msg) {
  return *msg->_impl_.timestamp_;
}
const ::foxglove::Color&
PointsAnnotation::_Internal::outline_color(const PointsAnnotation* msg) {
  return *msg->_impl_.outline_color_;
}
const ::foxglove::Color&
PointsAnnotation::_Internal::fill_color(const PointsAnnotation* msg) {
  return *msg->_impl_.fill_color_;
}
void PointsAnnotation::clear_timestamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
}
void PointsAnnotation::clear_points() {
  _impl_.points_.Clear();
}
void PointsAnnotation::clear_outline_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.outline_color_ != nullptr) {
    delete _impl_.outline_color_;
  }
  _impl_.outline_color_ = nullptr;
}
void PointsAnnotation::clear_outline_colors() {
  _impl_.outline_colors_.Clear();
}
void PointsAnnotation::clear_fill_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.fill_color_ != nullptr) {
    delete _impl_.fill_color_;
  }
  _impl_.fill_color_ = nullptr;
}
PointsAnnotation::PointsAnnotation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:foxglove.PointsAnnotation)
}
PointsAnnotation::PointsAnnotation(const PointsAnnotation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PointsAnnotation* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.points_){from._impl_.points_}
    , decltype(_impl_.outline_colors_){from._impl_.outline_colors_}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.outline_color_){nullptr}
    , decltype(_impl_.fill_color_){nullptr}
    , decltype(_impl_.thickness_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  if (from._internal_has_outline_color()) {
    _this->_impl_.outline_color_ = new ::foxglove::Color(*from._impl_.outline_color_);
  }
  if (from._internal_has_fill_color()) {
    _this->_impl_.fill_color_ = new ::foxglove::Color(*from._impl_.fill_color_);
  }
  ::memcpy(&_impl_.thickness_, &from._impl_.thickness_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.type_) -
    reinterpret_cast<char*>(&_impl_.thickness_)) + sizeof(_impl_.type_));
  // @@protoc_insertion_point(copy_constructor:foxglove.PointsAnnotation)
}

inline void PointsAnnotation::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.points_){arena}
    , decltype(_impl_.outline_colors_){arena}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.outline_color_){nullptr}
    , decltype(_impl_.fill_color_){nullptr}
    , decltype(_impl_.thickness_){0}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PointsAnnotation::~PointsAnnotation() {
  // @@protoc_insertion_point(destructor:foxglove.PointsAnnotation)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PointsAnnotation::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.points_.~RepeatedPtrField();
  _impl_.outline_colors_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.timestamp_;
  if (this != internal_default_instance()) delete _impl_.outline_color_;
  if (this != internal_default_instance()) delete _impl_.fill_color_;
}

void PointsAnnotation::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PointsAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.PointsAnnotation)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.points_.Clear();
  _impl_.outline_colors_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.outline_color_ != nullptr) {
    delete _impl_.outline_color_;
  }
  _impl_.outline_color_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.fill_color_ != nullptr) {
    delete _impl_.fill_color_;
  }
  _impl_.fill_color_ = nullptr;
  ::memset(&_impl_.thickness_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.thickness_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PointsAnnotation::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .foxglove.PointsAnnotation.Type type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::foxglove::PointsAnnotation_Type>(val));
        } else
          goto handle_unusual;
        continue;
      // repeated .foxglove.Point2 points = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_points(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .foxglove.Color outline_color = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_outline_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .foxglove.Color outline_colors = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_outline_colors(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .foxglove.Color fill_color = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_fill_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double thickness = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.thickness_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PointsAnnotation::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.PointsAnnotation)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // .foxglove.PointsAnnotation.Type type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // repeated .foxglove.Point2 points = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_points_size()); i < n; i++) {
    const auto& repfield = this->_internal_points(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .foxglove.Color outline_color = 4;
  if (this->_internal_has_outline_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::outline_color(this),
        _Internal::outline_color(this).GetCachedSize(), target, stream);
  }

  // repeated .foxglove.Color outline_colors = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_outline_colors_size()); i < n; i++) {
    const auto& repfield = this->_internal_outline_colors(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .foxglove.Color fill_color = 6;
  if (this->_internal_has_fill_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::fill_color(this),
        _Internal::fill_color(this).GetCachedSize(), target, stream);
  }

  // double thickness = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_thickness = this->_internal_thickness();
  uint64_t raw_thickness;
  memcpy(&raw_thickness, &tmp_thickness, sizeof(tmp_thickness));
  if (raw_thickness != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_thickness(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.PointsAnnotation)
  return target;
}

size_t PointsAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.PointsAnnotation)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .foxglove.Point2 points = 3;
  total_size += 1UL * this->_internal_points_size();
  for (const auto& msg : this->_impl_.points_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .foxglove.Color outline_colors = 5;
  total_size += 1UL * this->_internal_outline_colors_size();
  for (const auto& msg : this->_impl_.outline_colors_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.timestamp_);
  }

  // .foxglove.Color outline_color = 4;
  if (this->_internal_has_outline_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.outline_color_);
  }

  // .foxglove.Color fill_color = 6;
  if (this->_internal_has_fill_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.fill_color_);
  }

  // double thickness = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_thickness = this->_internal_thickness();
  uint64_t raw_thickness;
  memcpy(&raw_thickness, &tmp_thickness, sizeof(tmp_thickness));
  if (raw_thickness != 0) {
    total_size += 1 + 8;
  }

  // .foxglove.PointsAnnotation.Type type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PointsAnnotation::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PointsAnnotation::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PointsAnnotation::GetClassData() const { return &_class_data_; }


void PointsAnnotation::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PointsAnnotation*>(&to_msg);
  auto& from = static_cast<const PointsAnnotation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:foxglove.PointsAnnotation)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.points_.MergeFrom(from._impl_.points_);
  _this->_impl_.outline_colors_.MergeFrom(from._impl_.outline_colors_);
  if (from._internal_has_timestamp()) {
    _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  if (from._internal_has_outline_color()) {
    _this->_internal_mutable_outline_color()->::foxglove::Color::MergeFrom(
        from._internal_outline_color());
  }
  if (from._internal_has_fill_color()) {
    _this->_internal_mutable_fill_color()->::foxglove::Color::MergeFrom(
        from._internal_fill_color());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_thickness = from._internal_thickness();
  uint64_t raw_thickness;
  memcpy(&raw_thickness, &tmp_thickness, sizeof(tmp_thickness));
  if (raw_thickness != 0) {
    _this->_internal_set_thickness(from._internal_thickness());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PointsAnnotation::CopyFrom(const PointsAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.PointsAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointsAnnotation::IsInitialized() const {
  return true;
}

void PointsAnnotation::InternalSwap(PointsAnnotation* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.points_.InternalSwap(&other->_impl_.points_);
  _impl_.outline_colors_.InternalSwap(&other->_impl_.outline_colors_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PointsAnnotation, _impl_.type_)
      + sizeof(PointsAnnotation::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(PointsAnnotation, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PointsAnnotation::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_foxglove_2fPointsAnnotation_2eproto_getter, &descriptor_table_foxglove_2fPointsAnnotation_2eproto_once,
      file_level_metadata_foxglove_2fPointsAnnotation_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::foxglove::PointsAnnotation*
Arena::CreateMaybeMessage< ::foxglove::PointsAnnotation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::foxglove::PointsAnnotation >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
