// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/SceneUpdate.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_foxglove_2fSceneUpdate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_foxglove_2fSceneUpdate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/SceneEntity.pb.h"
#include "foxglove/SceneEntityDeletion.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_foxglove_2fSceneUpdate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_foxglove_2fSceneUpdate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_foxglove_2fSceneUpdate_2eproto;
namespace foxglove {
class SceneUpdate;
struct SceneUpdateDefaultTypeInternal;
extern SceneUpdateDefaultTypeInternal _SceneUpdate_default_instance_;
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> ::foxglove::SceneUpdate* Arena::CreateMaybeMessage<::foxglove::SceneUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace foxglove {

// ===================================================================

class SceneUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:foxglove.SceneUpdate) */ {
 public:
  inline SceneUpdate() : SceneUpdate(nullptr) {}
  ~SceneUpdate() override;
  explicit PROTOBUF_CONSTEXPR SceneUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SceneUpdate(const SceneUpdate& from);
  SceneUpdate(SceneUpdate&& from) noexcept
    : SceneUpdate() {
    *this = ::std::move(from);
  }

  inline SceneUpdate& operator=(const SceneUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneUpdate& operator=(SceneUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneUpdate* internal_default_instance() {
    return reinterpret_cast<const SceneUpdate*>(
               &_SceneUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SceneUpdate& a, SceneUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(SceneUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SceneUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SceneUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SceneUpdate& from) {
    SceneUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SceneUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "foxglove.SceneUpdate";
  }
  protected:
  explicit SceneUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeletionsFieldNumber = 1,
    kEntitiesFieldNumber = 2,
  };
  // repeated .foxglove.SceneEntityDeletion deletions = 1;
  int deletions_size() const;
  private:
  int _internal_deletions_size() const;
  public:
  void clear_deletions();
  ::foxglove::SceneEntityDeletion* mutable_deletions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntityDeletion >*
      mutable_deletions();
  private:
  const ::foxglove::SceneEntityDeletion& _internal_deletions(int index) const;
  ::foxglove::SceneEntityDeletion* _internal_add_deletions();
  public:
  const ::foxglove::SceneEntityDeletion& deletions(int index) const;
  ::foxglove::SceneEntityDeletion* add_deletions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntityDeletion >&
      deletions() const;

  // repeated .foxglove.SceneEntity entities = 2;
  int entities_size() const;
  private:
  int _internal_entities_size() const;
  public:
  void clear_entities();
  ::foxglove::SceneEntity* mutable_entities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntity >*
      mutable_entities();
  private:
  const ::foxglove::SceneEntity& _internal_entities(int index) const;
  ::foxglove::SceneEntity* _internal_add_entities();
  public:
  const ::foxglove::SceneEntity& entities(int index) const;
  ::foxglove::SceneEntity* add_entities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntity >&
      entities() const;

  // @@protoc_insertion_point(class_scope:foxglove.SceneUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntityDeletion > deletions_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntity > entities_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_foxglove_2fSceneUpdate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SceneUpdate

// repeated .foxglove.SceneEntityDeletion deletions = 1;
inline int SceneUpdate::_internal_deletions_size() const {
  return _impl_.deletions_.size();
}
inline int SceneUpdate::deletions_size() const {
  return _internal_deletions_size();
}
inline ::foxglove::SceneEntityDeletion* SceneUpdate::mutable_deletions(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.SceneUpdate.deletions)
  return _impl_.deletions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntityDeletion >*
SceneUpdate::mutable_deletions() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.SceneUpdate.deletions)
  return &_impl_.deletions_;
}
inline const ::foxglove::SceneEntityDeletion& SceneUpdate::_internal_deletions(int index) const {
  return _impl_.deletions_.Get(index);
}
inline const ::foxglove::SceneEntityDeletion& SceneUpdate::deletions(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.SceneUpdate.deletions)
  return _internal_deletions(index);
}
inline ::foxglove::SceneEntityDeletion* SceneUpdate::_internal_add_deletions() {
  return _impl_.deletions_.Add();
}
inline ::foxglove::SceneEntityDeletion* SceneUpdate::add_deletions() {
  ::foxglove::SceneEntityDeletion* _add = _internal_add_deletions();
  // @@protoc_insertion_point(field_add:foxglove.SceneUpdate.deletions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntityDeletion >&
SceneUpdate::deletions() const {
  // @@protoc_insertion_point(field_list:foxglove.SceneUpdate.deletions)
  return _impl_.deletions_;
}

// repeated .foxglove.SceneEntity entities = 2;
inline int SceneUpdate::_internal_entities_size() const {
  return _impl_.entities_.size();
}
inline int SceneUpdate::entities_size() const {
  return _internal_entities_size();
}
inline ::foxglove::SceneEntity* SceneUpdate::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.SceneUpdate.entities)
  return _impl_.entities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntity >*
SceneUpdate::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.SceneUpdate.entities)
  return &_impl_.entities_;
}
inline const ::foxglove::SceneEntity& SceneUpdate::_internal_entities(int index) const {
  return _impl_.entities_.Get(index);
}
inline const ::foxglove::SceneEntity& SceneUpdate::entities(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.SceneUpdate.entities)
  return _internal_entities(index);
}
inline ::foxglove::SceneEntity* SceneUpdate::_internal_add_entities() {
  return _impl_.entities_.Add();
}
inline ::foxglove::SceneEntity* SceneUpdate::add_entities() {
  ::foxglove::SceneEntity* _add = _internal_add_entities();
  // @@protoc_insertion_point(field_add:foxglove.SceneUpdate.entities)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::SceneEntity >&
SceneUpdate::entities() const {
  // @@protoc_insertion_point(field_list:foxglove.SceneUpdate.entities)
  return _impl_.entities_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_foxglove_2fSceneUpdate_2eproto
